// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/chat.tsx";
import * as $4 from "./routes/explore.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/privacy-and-happy-lawyers.tsx";
import * as $7 from "./routes/search.tsx";
import * as $8 from "./routes/settings/_layout.tsx";
import * as $9 from "./routes/settings/index.tsx";
import * as $10 from "./routes/settings/optics.tsx";
import * as $11 from "./routes/settings/privacy.tsx";
import * as $12 from "./routes/settings/sites.tsx";
import * as $13 from "./routes/webmasters.tsx";
import * as $$0 from "./islands/ApiClient.tsx";
import * as $$1 from "./islands/Discussions.tsx";
import * as $$2 from "./islands/ExploreSites.tsx";
import * as $$3 from "./islands/Improvements.tsx";
import * as $$4 from "./islands/ManageOptics.tsx";
import * as $$5 from "./islands/OpticsSelector.tsx";
import * as $$6 from "./islands/PrivacySelector.tsx";
import * as $$7 from "./islands/RegionSelector.tsx";
import * as $$8 from "./islands/SafeSearchSettings.tsx";
import * as $$9 from "./islands/SearchResultAdjust.tsx";
import * as $$10 from "./islands/Searchbar.tsx";
import * as $$11 from "./islands/SiteRanking.tsx";
import * as $$12 from "./islands/Snippet.tsx";
import * as $$13 from "./islands/chat/Chat.tsx";
import * as $$14 from "./islands/chat/state.ts";
import * as $$15 from "./islands/chat/traces.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/chat.tsx": $3,
    "./routes/explore.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/privacy-and-happy-lawyers.tsx": $6,
    "./routes/search.tsx": $7,
    "./routes/settings/_layout.tsx": $8,
    "./routes/settings/index.tsx": $9,
    "./routes/settings/optics.tsx": $10,
    "./routes/settings/privacy.tsx": $11,
    "./routes/settings/sites.tsx": $12,
    "./routes/webmasters.tsx": $13,
  },
  islands: {
    "./islands/ApiClient.tsx": $$0,
    "./islands/Discussions.tsx": $$1,
    "./islands/ExploreSites.tsx": $$2,
    "./islands/Improvements.tsx": $$3,
    "./islands/ManageOptics.tsx": $$4,
    "./islands/OpticsSelector.tsx": $$5,
    "./islands/PrivacySelector.tsx": $$6,
    "./islands/RegionSelector.tsx": $$7,
    "./islands/SafeSearchSettings.tsx": $$8,
    "./islands/SearchResultAdjust.tsx": $$9,
    "./islands/Searchbar.tsx": $$10,
    "./islands/SiteRanking.tsx": $$11,
    "./islands/Snippet.tsx": $$12,
    "./islands/chat/Chat.tsx": $$13,
    "./islands/chat/state.ts": $$14,
    "./islands/chat/traces.ts": $$15,
  },
  baseUrl: import.meta.url,
};

export default manifest;
