import { Event } from "./state.ts";

export const CHAT_TRACES: Event[][] = [
  [
    { type: "user", message: "what is the cheapest car to rent in iceland?" },
    {
      type: "alice",
      data: { type: "beginSearch", query: "cheapest car rental iceland" },
    },
    {
      type: "alice",
      data: {
        type: "searchResult",
        query: "cheapest car rental iceland",
        result: [{
          title: "Car Hire in Iceland - Worldwide Destinations",
          text:
            "find in Iceland? You will find car types such as mini, economy, compact, Full-Size and SUV cars. Popular rental cars are Hyundai I10, Toyota Yaris, Dacia Duster and Suzuki Vitara. Does my rental car have unlimited mileage when I book it for Iceland? Most car rentals in Iceland offer unlimited",
          url:
            "https://www.orbitcarhire.com/en/locations/car-rental-in-iceland/",
          site: "www.orbitcarhire.com",
        }, {
          title: "Cheap Flights from London to Caribbean from C$ 334 - KAYAK",
          text:
            'and disrespectful to two elderly passengers. It was NOT David. Charging $10 for entertainment was is terrible!!! Restrooms were filthy!!!" Pros: "The plain was new" Cons: "I asked for a blanket and they told me that they are out of blankets" Pros: "Good entertainment options, roomy seats" Cons: "Nothing I',
          url:
            "https://www.ca.kayak.com/flight-routes/London-YXU/Caribbean-0CB",
          site: "www.ca.kayak.com",
        }],
      },
    },
    { type: "alice", data: { type: "speaking", text: " The" } },
    { type: "alice", data: { type: "speaking", text: " cheapest" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " companies" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " Iceland" } },
    { type: "alice", data: { type: "speaking", text: " are" } },
    { type: "alice", data: { type: "speaking", text: " Mini" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Economy" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Sub" } },
    { type: "alice", data: { type: "speaking", text: "aru" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Suzuki" } },
    { type: "alice", data: { type: "speaking", text: " Vit" } },
    { type: "alice", data: { type: "speaking", text: "ara" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Toyota" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " Chevrolet" } },
    { type: "alice", data: { type: "speaking", text: "[" } },
    { type: "alice", data: { type: "speaking", text: "query" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: " source" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: "]." } },
    { type: "alice", data: { type: "speaking", text: " Popular" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " cars" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " Iceland" } },
    { type: "alice", data: { type: "speaking", text: " include" } },
    { type: "alice", data: { type: "speaking", text: " Toyota" } },
    { type: "alice", data: { type: "speaking", text: " 4" } },
    { type: "alice", data: { type: "speaking", text: "x" } },
    { type: "alice", data: { type: "speaking", text: "4" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Volkswagen" } },
    { type: "alice", data: { type: "speaking", text: " Golf" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Chevrolet" } },
    { type: "alice", data: { type: "speaking", text: " Orlando" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " Nissan" } },
    { type: "alice", data: { type: "speaking", text: " X" } },
    { type: "alice", data: { type: "speaking", text: "-" } },
    { type: "alice", data: { type: "speaking", text: "tra" } },
    { type: "alice", data: { type: "speaking", text: "il" } },
    { type: "alice", data: { type: "speaking", text: "[" } },
    { type: "alice", data: { type: "speaking", text: "query" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: " source" } },
    { type: "alice", data: { type: "speaking", text: " 2" } },
    { type: "alice", data: { type: "speaking", text: "]." } },
    { type: "alice", data: { type: "speaking", text: " It" } },
    { type: "alice", data: { type: "speaking", text: "'s" } },
    { type: "alice", data: { type: "speaking", text: " important" } },
    { type: "alice", data: { type: "speaking", text: " to" } },
    { type: "alice", data: { type: "speaking", text: " book" } },
    { type: "alice", data: { type: "speaking", text: " your" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " advance" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " compare" } },
    { type: "alice", data: { type: "speaking", text: " prices" } },
    { type: "alice", data: { type: "speaking", text: " across" } },
    { type: "alice", data: { type: "speaking", text: " different" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " companies" } },
    { type: "alice", data: { type: "speaking", text: "[" } },
    { type: "alice", data: { type: "speaking", text: "query" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: " source" } },
    { type: "alice", data: { type: "speaking", text: " 3" } },
    { type: "alice", data: { type: "speaking", text: "]." } },
    { type: "alice", data: { type: "speaking", text: " It" } },
    { type: "alice", data: { type: "speaking", text: "'s" } },
    { type: "alice", data: { type: "speaking", text: " also" } },
    { type: "alice", data: { type: "speaking", text: " important" } },
    { type: "alice", data: { type: "speaking", text: " to" } },
    { type: "alice", data: { type: "speaking", text: " respect" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " treat" } },
    { type: "alice", data: { type: "speaking", text: " it" } },
    { type: "alice", data: { type: "speaking", text: " with" } },
    { type: "alice", data: { type: "speaking", text: " respect" } },
    { type: "alice", data: { type: "speaking", text: "[" } },
    { type: "alice", data: { type: "speaking", text: "query" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: " source" } },
    { type: "alice", data: { type: "speaking", text: " 4" } },
    { type: "alice", data: { type: "speaking", text: "]." } },
    { type: "alice", data: { type: "speaking", text: " It" } },
    { type: "alice", data: { type: "speaking", text: "'s" } },
    { type: "alice", data: { type: "speaking", text: " advis" } },
    { type: "alice", data: { type: "speaking", text: "able" } },
    { type: "alice", data: { type: "speaking", text: " to" } },
    { type: "alice", data: { type: "speaking", text: " book" } },
    { type: "alice", data: { type: "speaking", text: " your" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " advance" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " compare" } },
    { type: "alice", data: { type: "speaking", text: " prices" } },
    { type: "alice", data: { type: "speaking", text: " across" } },
    { type: "alice", data: { type: "speaking", text: " different" } },
    { type: "alice", data: { type: "speaking", text: " rental" } },
    { type: "alice", data: { type: "speaking", text: " car" } },
    { type: "alice", data: { type: "speaking", text: " companies" } },
    { type: "alice", data: { type: "speaking", text: "[" } },
    { type: "alice", data: { type: "speaking", text: "query" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: " source" } },
    { type: "alice", data: { type: "speaking", text: " 1" } },
    { type: "alice", data: { type: "speaking", text: "]." } },
    { type: "alice", data: { type: "done", state: "" } },
  ],
  [
    { type: "user", message: "who is elon musk?" },
    { type: "alice", data: { type: "beginSearch", query: "elon musk" } },
    {
      type: "alice",
      data: {
        type: "searchResult",
        query: "elon musk",
        result: [{
          title:
            "Илон Маск упомянул свой суперкомпьютер Dojo и взвинтил курс криптовалюты на 500% - News Tech",
          text:
            "Илон Маск упомянул свой суперкомпьютер Dojo и взвинтил курс криптовалюты на 500% by · 15.01.2022 Генеральный директор Tesla и SpaceX Илон Маск (Elon Musk) одним словом (Dojo) вызвал стремительный рост одноименной криптовалюты. За полчаса она выросла более чем на 500%. Маск ответил на следующее сообщение: «Возможно, когда-нибудь, когда у нас",
          url:
            "https://newstech.cc/%D0%B8%D0%BB%D0%BE%D0%BD-%D0%BC%D0%B0%D1%81%D0%BA-%D1%83%D0%BF%D0%BE%D0%BC%D1%8F%D0%BD%D1%83%D0%BB-%D1%81%D0%B2%D0%BE%D0%B9-%D1%81%D1%83%D0%BF%D0%B5%D1%80%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82/",
          site: "newstech.cc",
        }, {
          title: "Scarica da Pinterest gli sticker più divertenti per WhatsApp",
          text:
            "2019 (66 TWh). Quando a dicembre è stato nominato Persona dell’anno 2021 dalla rivista Time, Elon Musk ha affermato che Bitcoin era un buon modo per immagazzinare valore, ma Dogecoin , “anche se è stato creato per scherzo, è un mezzo di scambio migliore “. Nonostante il successo del Dogecoin",
          url:
            "https://syrus.blog/scarica-da-pinterest-gli-sticker-piu-divertenti-per-whatsapp-9024.html",
          site: "syrus.blog",
        }, {
          title: "Nio ES8 2018 - Wheel  Tire Sizes, PCD, Offset and Rims specs",
          text:
            "14, 2018 While Elon Musk is struggling with his board (and possibly reality) in an attempt at taking electric vehicle builder Tesla private, another EV Mar 3, 2021 Nio is planning to significantly accelerate its manufacturing in H2 2021 as it gears up for an EV Nio electric vehicles Tesla",
          url: "https://investerarpengarpsck.firebaseapp.com/73942/16268.html",
          site: "investerarpengarpsck.firebaseapp.com",
        }, {
          title:
            "Votre montre fitness bientôt remboursée par l'Assurance Maladie ?",
          text:
            "rapport est transformé en projet de loi et adopté par l’Assemblée nationale. Alors que l’élection présidentielle se rapproche, c’est sans doute un dossier qui concernera le prochain gouvernement. Elon Musk, ce millionnaire prêt à courir tous les risques pour améliorer la vie humaine, […] More Par Sibelle 14 décembre 2021,",
          url: "https://technplay.com/objets-connectes-assurance-maladie-1301/",
          site: "technplay.com",
        }, {
          title: "Centralize – Page 2 – My personal blog",
          text:
            "request to the office of Prime Minister Narendra Modi of India. Musk did not identify the “issues” he was working on in his Twitter post. The Indian market for premium EVs is still in its infancy and there is a shortage of charging infrastructure. Of the 2.4 million cars sold",
          url: "https://centralize.noidasoft.com/page/2/",
          site: "centralize.noidasoft.com",
        }, {
          title:
            "Welche Ist Die Beste App Für Kryptowährung – Wann steigen kryptowährungen wieder?",
          text:
            "als Macro Influencer eingestuft werden. Zu dem Kurseinbruch der Digitalwährungen kommt weitere Probleme hinzu, dem Anwender eine Anlageberatung zukommen zu lassen. Mehr: Tesla-Gründer Elon Musk will Dogecoin effizienter machen und löst neue Kursrally aus, noch ihn bei Investmententscheiden zu unterstützen. Generell werden von Uhr am meisten Posts hochgeladen, sondern auch",
          url:
            "https://www.kampling-musikagentur.de/welche-ist-die-beste-app-f%C3%BCr-kryptow%C3%A4hrung/",
          site: "www.kampling-musikagentur.de",
        }, {
          title:
            "When Is The Difference Between Btu Protocol Core And Usd Dropping?",
          text:
            "to all musk coins that have to worry about literally anything. solana gems. ✨🚀 hypermoon is fair launching right now!. ​, case #06037888. where is it??. 💲 secure your future regarding money., last 1.5 days have pass is your computer, whereas with ledger, metamask communicates with your help, where can",
          url:
            "https://btu-protocol.luberdom.eu/when-is-the-difference-between-btu-protocol-core-and-usd-dropping",
          site: "btu-protocol.luberdom.eu",
        }, {
          title: "Krypto Wert Rechner | Wer beeinflusst kryptowährung?",
          text:
            "wurde abgelehnt und die Kündigung wurde solange rausgezögert, sondern werden von Smart Contracts ausgestellt. Elon Musks Kurswechsel in Sachen Zahlungsmittel für Tesla und das gestern vom chinesischen Finanzindustrieverband ausgesprochene Verbot für Krypto-Geschäfte haben die Kurskorrektur befeuert, die auf anderen Kryptonetzwerken aufbauen. Für den Handel mit Aktien oder anderen Finanzinstrumenten müssen",
          url: "https://www.kampling-musikagentur.de/krypto-wert-rechner/",
          site: "www.kampling-musikagentur.de",
        }, {
          title:
            "CDC claims it has authority to use police to do everything you see going on in Australia; and Congress agrees – LeoHohmann.com",
          text:
            "predicted [about ten years ago] that by 2029 artificial intelligence [AI] would fuse with the human mind,” Whitehead said. “Elon Musk said at least when there’s an evil dictator that’s human it’s going to die, but with AI it will live forever. Everything is being watched. Basically everything on the",
          url:
            "https://leohohmann.com/2021/09/27/cdc-claims-it-has-authority-to-use-police-to-do-everything-you-see-going-on-in-australia-and-congress-agrees/?like_comment=37749&_wpnonce=fd26722776",
          site: "leohohmann.com",
        }, {
          title: "fuckedgaijin • Frequently Asked Questions",
          text:
            "instead. Smilies, or Emoticons, are small images which can be used to express a feeling using a short code, e.g. :) denotes happy, while :( denotes sad. The full list of emoticons can be seen in the posting form. Try not to overuse smilies, however, as they can quickly render",
          url:
            "https://www.fuckedgaijin.com/forums/faq.php?sid=1a142ac7bac6e9cbde0b38bd77add694",
          site: "www.fuckedgaijin.com",
        }, {
          title:
            "UnNews:Bird Flu found in UK man - Uncyclopedia, the content-free encyclopedia",
          text:
            "us here at UnNews towers are not panicking, panicking, PANICKING!!!!!",
          url:
            "https://en.uncyclopedia.co/wiki/UnNews:Bird_Flu_found_in_UK_man",
          site: "en.uncyclopedia.co",
        }, {
          title: "WAS SHE REALLY A SAINT? – Talk of the Town",
          text:
            "Talk of the Town! “ Learning English is like working out: you can never stop practicing! At Talk of the Town, I can go beyond language, and stay informed about what is going on in the world. “ ” As aulas em forma de debates do Talk of the Town",
          url:
            "https://www.talkofthetown.com.br/debates/was-she-really-a-saint/",
          site: "www.talkofthetown.com.br",
        }, {
          title: "kim kardashian – Celebs Fast!",
          text:
            "by celebsfast Wednesday, March 31, 2021 The Kardashian’s can be a very secretive family. We’ve compiled a list of 15 secrets that Kim K has let slip over the years. Kim Kardashian has always said that she simply wanted to get married and have children. The Kardashian revealed that success",
          url: "http://celebsfast.com/tag/kim-kardashian/",
          site: "celebsfast.com",
        }, {
          title:
            "Yeni Alman hükümeti esrar kullanımını yasallaştırmaya hazırlanıyor |",
          text: "",
          url:
            "https://www.bayernses.de/yeni-alman-hugrupti-esrar-kullanimini-yasallastirmaya-hazirlaniyor/",
          site: "www.bayernses.de",
        }, {
          title: "freedom | MRCTV",
          text:
            'partake in the vaccine is making me question my future in the @nfl," Arizona Cardinals wide receiver DeAndre Hopkins wrote in a now-deleted... Communism in Cuba, Gimenez wrote, has “led to misery, poverty, and stifled basic and fundamental human rights.” The New York Times was blasted on social media Sunday',
          url: "https://www.mrctv.org/tag/freedom",
          site: "www.mrctv.org",
        }, {
          title:
            "İnstagram | Teknoloji Sitesi | Teknoloji Haberleri 2019 | Teknoloji Siteleri İsimleri",
          text: "",
          url: "http://www.teknolojisitesi.net/etiket/instagram",
          site: "www.teknolojisitesi.net",
        }, {
          title: "Mass Effect: Andromeda update | iTech Post",
          text:
            "Copyright © 2022 iTech Post All Rights Reserved. Reproduction in whole or in part without permission is prohibited.",
          url: "http://www.itechpost.com/tags/mass-effect-andromeda-update",
          site: "www.itechpost.com",
        }, {
          title:
            "Lockdown travel rules: Can I travel abroad during national lockdown? – Latest World News",
          text:
            "leave isolation early. CEO of travel consultancy, The PC Agency Paul Charles said on Twitter this evening that this is “traditionally” a busy period for travel companies. He explained: “Travel companies and airlines now need to focus on taking bookings in the coming weeks, traditionally the busiest booking period of",
          url:
            "https://mycitybeat.com/lockdown-travel-rules-can-i-travel-abroad-during-national-lockdown/",
          site: "mycitybeat.com",
        }, {
          title: "neutron stars Archives - Popular Science Part",
          text:
            "Astronomers use ESA’s X-ray space observatory XMM-Newton have spotted for the first time an enigmatic cloud of high-energy particles which called a wind nebula around a magnetar. Neutron stars are …",
          url: "https://www.sciencepart.com/tag/neutron-stars/",
          site: "www.sciencepart.com",
        }, {
          title:
            "China BANS Flaunting Wealth On Social Media | The Kyle Kulinski Show",
          text:
            "Support The Show On Patreon!: https://www.patreon.com/seculartalk Subscribe to Krystal Kyle & Friends On Substack!: https://krystalkyleandfriends.substack.com Follow Kyle on Twitter: http://www.twitter.com/kylekulinski #KyleKulinski #SecularTalk",
          url: "https://independentnewscasts.com/v/qT3_61onMTo",
          site: "independentnewscasts.com",
        }],
      },
    },
    {
      type: "alice",
      data: { type: "beginSearch", query: "elon musk bayes net" },
    },
    {
      type: "alice",
      data: {
        type: "searchResult",
        query: "elon musk bayes net",
        result: [],
      },
    },
    // {
    //   type: "alice",
    //   data: { type: "beginSearch", query: "elon musk bayes net" },
    // },
    { type: "alice", data: { type: "speaking", text: " El" } },
    { type: "alice", data: { type: "speaking", text: "on" } },
    { type: "alice", data: { type: "speaking", text: " Musk" } },
    { type: "alice", data: { type: "speaking", text: " is" } },
    { type: "alice", data: { type: "speaking", text: " a" } },
    { type: "alice", data: { type: "speaking", text: " renowned" } },
    { type: "alice", data: { type: "speaking", text: " entrepreneur" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " engineer" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " innov" } },
    { type: "alice", data: { type: "speaking", text: "ator" } },
    { type: "alice", data: { type: "speaking", text: " who" } },
    { type: "alice", data: { type: "speaking", text: " has" } },
    { type: "alice", data: { type: "speaking", text: " made" } },
    { type: "alice", data: { type: "speaking", text: " significant" } },
    { type: "alice", data: { type: "speaking", text: " contributions" } },
    { type: "alice", data: { type: "speaking", text: " to" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " development" } },
    { type: "alice", data: { type: "speaking", text: " of" } },
    { type: "alice", data: { type: "speaking", text: " artificial" } },
    { type: "alice", data: { type: "speaking", text: " intelligence" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " electric" } },
    { type: "alice", data: { type: "speaking", text: " cars" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " space" } },
    { type: "alice", data: { type: "speaking", text: " exploration" } },
    { type: "alice", data: { type: "speaking", text: "." } },
    { type: "alice", data: { type: "speaking", text: " Musk" } },
    { type: "alice", data: { type: "speaking", text: " was" } },
    { type: "alice", data: { type: "speaking", text: " born" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " Pret" } },
    { type: "alice", data: { type: "speaking", text: "oria" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " South" } },
    { type: "alice", data: { type: "speaking", text: " Africa" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " 1971" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " is" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " founder" } },
    { type: "alice", data: { type: "speaking", text: " of" } },
    { type: "alice", data: { type: "speaking", text: " Space" } },
    { type: "alice", data: { type: "speaking", text: "X" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Tesla" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " The" } },
    { type: "alice", data: { type: "speaking", text: " B" } },
    { type: "alice", data: { type: "speaking", text: "oring" } },
    { type: "alice", data: { type: "speaking", text: " Company" } },
    { type: "alice", data: { type: "speaking", text: "." } },
    { type: "alice", data: { type: "speaking", text: " Musk" } },
    { type: "alice", data: { type: "speaking", text: " has" } },
    { type: "alice", data: { type: "speaking", text: " received" } },
    { type: "alice", data: { type: "speaking", text: " numerous" } },
    { type: "alice", data: { type: "speaking", text: " awards" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " honors" } },
    { type: "alice", data: { type: "speaking", text: " for" } },
    { type: "alice", data: { type: "speaking", text: " his" } },
    { type: "alice", data: { type: "speaking", text: " contributions" } },
    { type: "alice", data: { type: "speaking", text: " to" } },
    { type: "alice", data: { type: "speaking", text: " science" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " technology" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " including" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " Legion" } },
    { type: "alice", data: { type: "speaking", text: " of" } },
    { type: "alice", data: { type: "speaking", text: " Honor" } },
    { type: "alice", data: { type: "speaking", text: " award" } },
    { type: "alice", data: { type: "speaking", text: " from" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " French" } },
    { type: "alice", data: { type: "speaking", text: " government" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " the" } },
    { type: "alice", data: { type: "speaking", text: " Kyoto" } },
    { type: "alice", data: { type: "speaking", text: " Prize" } },
    { type: "alice", data: { type: "speaking", text: " in" } },
    { type: "alice", data: { type: "speaking", text: " Advanced" } },
    { type: "alice", data: { type: "speaking", text: " Soci" } },
    { type: "alice", data: { type: "speaking", text: "eties" } },
    { type: "alice", data: { type: "speaking", text: "." } },
    { type: "alice", data: { type: "speaking", text: " Musk" } },
    { type: "alice", data: { type: "speaking", text: " is" } },
    { type: "alice", data: { type: "speaking", text: " also" } },
    { type: "alice", data: { type: "speaking", text: " an" } },
    { type: "alice", data: { type: "speaking", text: " advocate" } },
    { type: "alice", data: { type: "speaking", text: " for" } },
    { type: "alice", data: { type: "speaking", text: " science" } },
    { type: "alice", data: { type: "speaking", text: " literacy" } },
    { type: "alice", data: { type: "speaking", text: " and" } },
    { type: "alice", data: { type: "speaking", text: " has" } },
    { type: "alice", data: { type: "speaking", text: " advocated" } },
    { type: "alice", data: { type: "speaking", text: " for" } },
    { type: "alice", data: { type: "speaking", text: " increased" } },
    { type: "alice", data: { type: "speaking", text: " funding" } },
    { type: "alice", data: { type: "speaking", text: " for" } },
    { type: "alice", data: { type: "speaking", text: " STEM" } },
    { type: "alice", data: { type: "speaking", text: " education" } },
    { type: "alice", data: { type: "speaking", text: "." } },
    { type: "alice", data: { type: "done", state: "" } },
    { type: "user", message: "does he have any siblings?" },
    {
      type: "alice",
      data: { type: "beginSearch", query: "siblings of hezbollah" },
    },
    {
      type: "alice",
      data: {
        type: "searchResult",
        query: "siblings of hezbollah",
        result: [],
      },
    },
    // {
    //   type: "alice",
    //   data: { type: "beginSearch", query: "siblings of hezbollah" },
    // },
    { type: "alice", data: { type: "speaking", text: " Yes" } },
    { type: "alice", data: { type: "speaking", text: "," } },
    { type: "alice", data: { type: "speaking", text: " Hassan" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: " has" } },
    { type: "alice", data: { type: "speaking", text: " siblings" } },
    { type: "alice", data: { type: "speaking", text: "." } },
    { type: "alice", data: { type: "speaking", text: " His" } },
    { type: "alice", data: { type: "speaking", text: " siblings" } },
    { type: "alice", data: { type: "speaking", text: " are" } },
    { type: "alice", data: { type: "speaking", text: ":" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Ali" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Bass" } },
    { type: "alice", data: { type: "speaking", text: "el" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "speaking", text: "ah" } },
    { type: "alice", data: { type: "speaking", text: "\\n" } },
    { type: "alice", data: { type: "speaking", text: "*" } },
    { type: "alice", data: { type: "speaking", text: " Fat" } },
    { type: "alice", data: { type: "speaking", text: "ima" } },
    { type: "alice", data: { type: "speaking", text: " Nas" } },
    { type: "alice", data: { type: "speaking", text: "r" } },
    { type: "alice", data: { type: "speaking", text: "all" } },
    { type: "alice", data: { type: "done", state: "" } },
  ],
];
