#!.venv/bin/python3
import os
import transformers
import torch
import sys

MODEL = "deepset/tinyroberta-squad2"

question = "Where is amazon rain forest located"
context = """The Amazon rainforest (Portuguese: Floresta Amazônica or Amazônia; Spanish: Selva Amazónica, Amazonía or usually Amazonia; French: Forêt amazonienne; Dutch: Amazoneregenwoud), also known in English as Amazonia or the Amazon Jungle, is a moist broadleaf forest that covers most of the Amazon basin of South America. This basin encompasses 7,000,000 square kilometres (2,700,000 sq mi), of 
which 5,500,000 square kilometres (2,100,000 sq mi) are covered by the rainforest. This region includes territory belonging to nine nations. 
The majority of the forest is contained within Brazil, with 60% of the rainforest, followed by Peru with 13%, Colombia with 10%, and with 
minor amounts in Venezuela, Ecuador, Bolivia, Guyana, Suriname and French Guiana. States or departments in four nations contain 
"Amazonas" in their names. The Amazon represents over half of the planet's remaining rainforests, and comprises the largest and most biodiverse tract 
of tropical rainforest in the world, with an estimated 390 billion individual trees divided into 16,000 species."""

if os.path.exists("data/qa_model/"):
    print("data/qa_model/ already exists. Exiting...")
    sys.exit()

os.system("mkdir data/qa_model")

model = transformers.AutoModelForQuestionAnswering.from_pretrained(MODEL)

model.eval()
for p in model.parameters():
    p.requires_grad_(False)

tokenizer = transformers.AutoTokenizer.from_pretrained(MODEL)
tokenizer.save_pretrained("data/qa_model")

features = tokenizer(
    question,
    context,
    padding="max_length",
    truncation=True,
    return_tensors="pt",
)
input_ids = features["input_ids"]
attention_mask = features["attention_mask"]


def run_model(input_ids, attention_mask):
    res = model(input_ids=input_ids, attention_mask=attention_mask, return_dict=False)
    return res


traced_model = torch.jit.trace(run_model, ((input_ids, attention_mask)))

traced_model.save("data/qa_model/model.pt")
